title: Campusradio Wiki
host: 'http://localhost'
port: 80
paths:
  repo: ./repo
  data: ./data

db: 'mongodb://wikidb:27017/wiki'
git: false
lang: en
public: false

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

auth:
  defaultReadAccess: true
  local:
    enabled: false
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: true
    clientId: CLIENT_ID
    clientSecret: CLIENT_SECRET

# 256 String
sessionSecret: abcdefgh1238217348967

theme:
  primary: indigo
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
